/**
 * Enterprise Audit catalog.
 *
 * Declares the 8 category sections and every capability card in them, each with
 * a real Lucide icon, plain-English "what / why" copy, a paste-ready fix prompt,
 * and the detection rules used to light the card up against a real project:
 *
 *  - `nodeTypes`     → Detected when any of these infra node types is present.
 *  - `partialTypes`  → Partial when one of these related types is present.
 *  - `keywords`      → scanned against the infra evidence corpus (→ Detected) and
 *                      against pipeline findings (HIGH/CRITICAL → Critical Gap,
 *                      MEDIUM → Missing).
 *  - `criticalIfMissing` → when nothing is found, the card is a Critical Gap
 *                      because its absence is a security/reliability risk.
 *  - `securityStep`  → only the security-checks pipeline findings are considered.
 *
 * Detection itself lives in EnterpriseAudit.tsx; this file is pure data.
 */

import {
  ArrowDownUp,
  BarChart3,
  BellRing,
  Bird,
  Boxes,
  Brain,
  Bug,
  CircuitBoard,
  ClipboardList,
  CloudOff,
  Combine,
  Container,
  Copy,
  Database,
  DollarSign,
  DoorOpen,
  Expand,
  Eye,
  FileCheck,
  FileCode,
  FileKey,
  Fingerprint,
  FlaskConical,
  Gauge,
  GitBranch,
  GitFork,
  GitMerge,
  Globe,
  Globe2,
  HardDrive,
  HeartPulse,
  Hourglass,
  KeyRound,
  Layers,
  LifeBuoy,
  Lock,
  MonitorCheck,
  Network,
  Plug,
  RefreshCw,
  Save,
  Scale,
  ScrollText,
  Search,
  Send,
  ServerCog,
  Shield,
  ShieldAlert,
  ShieldCheck,
  SlidersHorizontal,
  Smile,
  Split,
  SprayCan,
  Timer,
  TrendingUp,
  UserCog,
  Workflow,
  Wrench,
  Zap,
  type LucideIcon,
} from 'lucide-react';
import type { InfraNodeType } from '@archlab/shared';

export interface CardDef {
  id: string;
  label: string;
  icon: LucideIcon;
  what: string;
  why: string;
  fix: string;
  /** Detected when any of these infra node types is present. */
  nodeTypes?: InfraNodeType[];
  /** Partial when one of these related types is present (but not a full match). */
  partialTypes?: InfraNodeType[];
  /** Distinctive keywords for corpus + findings scanning (whole-word matched). */
  keywords?: string[];
  /**
   * npm package names (or CI/scan config-file markers like ".github/workflows")
   * whose presence in the project proves this capability → Detected.
   */
  packages?: string[];
  /**
   * Keywords whose presence is an anti-pattern (e.g. dangerouslySetInnerHTML).
   * Any match forces Critical Gap — presence is the risk, never proof.
   */
  negativeKeywords?: string[];
  /** Absence is itself a security/reliability risk → Critical Gap when missing. */
  criticalIfMissing?: boolean;
  /**
   * Operational/process capability that cannot be proven by static code scan.
   * Corpus keyword hits never promote it; default Missing until a structural
   * node type, a real dependency, or an Agent Team finding proves it.
   */
  requiresProof?: boolean;
  /** Only consider security-checks pipeline findings for this card. */
  securityStep?: boolean;
}

export interface SectionDef {
  id: string;
  title: string;
  color: string;
  cards: CardDef[];
}

export const ENTERPRISE_SECTIONS: SectionDef[] = [
  {
    id: 'infrastructure',
    title: 'Infrastructure',
    color: '#06B6D4',
    cards: [
      {
        id: 'cdn',
        label: 'CDN',
        icon: Globe,
        nodeTypes: ['cdn'],
        keywords: ['cloudfront', 'cloudflare', 'fastly', 'cdn'],
        what: 'A content delivery network caches static assets at edge locations close to users.',
        why: 'Cuts latency and origin load, and is the first line of defense for global traffic.',
        fix: 'Add a CDN (CloudFront or Cloudflare) in front of the app edge and cache static assets with sensible cache-control headers and deploy-time invalidation.',
      },
      {
        id: 'load-balancer',
        label: 'Load Balancer',
        icon: Scale,
        nodeTypes: ['load-balancer'],
        keywords: ['nginx', 'proxy_pass', 'load balanc', 'elb', 'haproxy'],
        what: 'A load balancer distributes traffic across redundant application instances.',
        why: 'Without it a single instance is a hard ceiling on throughput and a single point of failure.',
        fix: 'Put a load balancer (ALB, NGINX, or your platform default) in front of the app tier and run at least two instances behind it.',
      },
      {
        id: 'api-gateway',
        label: 'API Gateway',
        icon: DoorOpen,
        nodeTypes: ['api-gateway'],
        keywords: ['gateway', 'express', 'fastify', 'kong'],
        what: 'A single entry point that handles routing, rate limiting, and request shaping.',
        why: 'Centralizes cross-cutting concerns instead of scattering them across services.',
        fix: 'Introduce an API gateway that owns routing, auth verification, and rate limiting before traffic reaches services.',
      },
      {
        id: 'microservices',
        label: 'Microservices',
        icon: Boxes,
        nodeTypes: ['microservice'],
        keywords: ['microservice', 'service', '.listen', 'createserver'],
        what: 'Independently deployable units that each own a slice of the domain.',
        why: 'Enables independent scaling and deploys, at the cost of operational complexity.',
        fix: 'Split the monolith along clear domain boundaries into independently deployable services with their own data ownership.',
      },
      {
        id: 'auth-service',
        label: 'Auth Service',
        icon: KeyRound,
        nodeTypes: ['auth-service'],
        keywords: ['jwt', 'passport', 'clerk', 'oauth', 'auth'],
        packages: ['passport', 'jsonwebtoken', '@clerk/clerk-sdk-node', 'next-auth', '@auth/core'],
        criticalIfMissing: true,
        what: 'A dedicated service that verifies identity and issues/validates tokens.',
        why: 'Unauthenticated endpoints are the most common and most damaging vulnerability class.',
        fix: 'Add an authentication layer that verifies a signed token in middleware before protected handlers and returns 401/403 consistently.',
      },
      {
        id: 'cache',
        label: 'Cache',
        icon: Zap,
        nodeTypes: ['cache', 'redis'],
        keywords: ['redis', 'ioredis', 'memcached', 'cache'],
        packages: ['ioredis', 'redis', 'node-cache', 'memcached'],
        what: 'An in-memory store for hot data so repeated reads avoid the database.',
        why: 'Absorbs read load and is usually the cheapest large performance win.',
        fix: 'Add a Redis cache with read-through/write-through helpers for the hottest queries and invalidate on writes.',
      },
      {
        id: 'message-queue',
        label: 'Message Queue',
        icon: Send,
        nodeTypes: ['pubsub-topic', 'message-queue'],
        keywords: ['bull', 'rabbitmq', 'amqplib', 'kafka', 'queue', 'pubsub'],
        packages: ['bullmq', 'bull', 'amqplib', 'kafkajs', '@aws-sdk/client-sqs'],
        what: 'A buffer that decouples producers from consumers for async work.',
        why: 'Smooths traffic spikes and keeps slow work off the request path.',
        fix: 'Introduce a message queue (BullMQ, RabbitMQ, or SQS) for background work, with a dead letter queue for failed messages.',
      },
      {
        id: 'database',
        label: 'Database',
        icon: Database,
        nodeTypes: ['postgres', 'mysql', 'mongodb', 'redis'],
        keywords: ['postgres', 'mysql', 'mongo', 'prisma', 'sequelize', 'typeorm', 'drizzle'],
        packages: ['@prisma/client', 'prisma', 'sequelize', 'typeorm', 'drizzle-orm', 'mongoose', 'pg', 'mysql2'],
        what: 'The system of record for structured, persistent data.',
        why: 'Every stateful product needs durable, queryable storage with transactional guarantees.',
        fix: 'Provision a managed relational database (PostgreSQL) and access it through an ORM or query builder with migrations.',
      },
      {
        id: 'object-storage',
        label: 'Object Storage',
        icon: HardDrive,
        nodeTypes: ['private-bucket', 'public-bucket'],
        keywords: ['s3', 'cloud storage', 'storage.from', 'blob', 'bucket'],
        packages: ['@aws-sdk/client-s3', 'aws-sdk', '@google-cloud/storage', '@supabase/storage-js'],
        what: 'Bucket storage for files: uploads, assets, and backups.',
        why: 'Keeps large binary data out of the database and serves it efficiently.',
        fix: 'Use a private object storage bucket and serve files through short-lived signed URLs instead of public paths.',
      },
      {
        id: 'kms',
        label: 'KMS',
        icon: FileKey,
        nodeTypes: ['kms'],
        keywords: ['kms', 'vault', 'createcipheriv', 'key management'],
        packages: ['@aws-sdk/client-kms', 'node-vault'],
        what: 'A key management service that stores and gates cryptographic keys.',
        why: 'Centralizes encryption keys so secrets are never hardcoded or sprawled.',
        fix: 'Adopt a KMS (AWS KMS, GCP KMS, or Vault) to manage encryption keys and scope which services can decrypt.',
      },
      {
        id: 'service-mesh',
        label: 'Service Mesh',
        icon: Network,
        requiresProof: true,
        keywords: ['istio', 'linkerd', 'envoy', 'service mesh', 'consul connect'],
        what: 'A dedicated layer for service-to-service traffic: mTLS, retries, and routing.',
        why: 'Standardizes east-west networking and security across many services.',
        fix: 'Evaluate a service mesh (Istio or Linkerd) once you run several services that need mTLS and traffic policy.',
      },
      {
        id: 'container-orchestration',
        label: 'Container Orchestration',
        icon: Container,
        requiresProof: true,
        keywords: ['kubernetes', 'k8s', 'docker', 'helm', 'ecs', 'nomad'],
        what: 'A scheduler (Kubernetes, ECS) that runs and heals containerized workloads.',
        why: 'Provides self-healing, rolling deploys, and horizontal scaling primitives.',
        fix: 'Containerize the services and run them on an orchestrator (Kubernetes or ECS) with health probes and resource limits.',
      },
    ],
  },
  {
    id: 'principles',
    title: 'System Design Principles',
    color: '#6366F1',
    cards: [
      {
        id: 'scalability',
        label: 'Scalability',
        icon: TrendingUp,
        nodeTypes: ['load-balancer'],
        partialTypes: ['microservice', 'cache'],
        keywords: ['horizontal-scaling', 'auto-scale'],
        what: 'The ability to handle more load by adding resources.',
        why: 'Determines whether the system survives growth or falls over at the next traffic peak.',
        fix: 'Make the app tier stateless and scale it horizontally behind a load balancer with autoscaling rules.',
      },
      {
        id: 'reliability',
        label: 'Reliability',
        icon: ShieldCheck,
        partialTypes: ['load-balancer'],
        keywords: ['uptime', 'sla', 'availability'],
        criticalIfMissing: true,
        what: 'The system keeps working correctly despite partial failures.',
        why: 'Reliability is what users actually experience as quality; outages erode trust fast.',
        fix: 'Add redundancy, health checks, retries, and failover so no single component failure takes the system down.',
      },
      {
        id: 'security',
        label: 'Security',
        icon: Shield,
        nodeTypes: ['auth-service', 'kms'],
        keywords: ['auth', 'encrypt', 'tls', 'csrf', 'xss', 'rbac'],
        securityStep: true,
        criticalIfMissing: true,
        what: 'Protecting data and access against misuse and attack.',
        why: 'A single breach can be existential; security must be designed in, not bolted on.',
        fix: 'Establish auth, input validation, encryption in transit and at rest, and least-privilege access across the system.',
      },
      {
        id: 'performance',
        label: 'Performance',
        icon: Gauge,
        nodeTypes: ['cache', 'cdn'],
        keywords: ['cache', 'cdn', 'latency', 'index', 'lazy'],
        what: 'Low latency and efficient resource use under load.',
        why: 'Slow responses directly cost conversions and compound under scale.',
        fix: 'Profile hot paths, add caching and database indexes, and lazy-load heavy assets on the frontend.',
      },
      {
        id: 'maintainability',
        label: 'Maintainability',
        icon: Wrench,
        keywords: ['test', 'lint', 'typescript', 'eslint', 'prettier', 'ci'],
        what: 'How easily the codebase can be changed safely over time.',
        why: 'Most of a system’s cost is maintenance; brittle code slows every future change.',
        fix: 'Enforce linting, type checking, and a test suite in CI so changes stay safe and reviewable.',
      },
      {
        id: 'cost-optimization',
        label: 'Cost Optimization',
        icon: DollarSign,
        keywords: ['cost', 'budget', 'autoscal', 'spot', 'reserved', 'rightsiz'],
        what: 'Spending only what the workload actually needs.',
        why: 'Unmanaged cloud cost balloons silently and is hard to claw back later.',
        fix: 'Add cost monitoring, right-size instances, and use autoscaling so you pay for demand rather than peak.',
      },
      {
        id: 'flexibility',
        label: 'Flexibility',
        icon: SlidersHorizontal,
        keywords: ['feature-flag', 'launchdarkly', 'unleash'],
        packages: ['launchdarkly-node-server-sdk', 'unleash-client', '@unleash/proxy-client'],
        what: 'The ability to change behavior without redeploying.',
        why: 'Feature flags and config decouple release from deploy and de-risk rollouts.',
        fix: 'Introduce a feature-flag/config system so behavior can be toggled per environment without a redeploy.',
      },
      {
        id: 'modular-design',
        label: 'Modular Design',
        icon: Layers,
        nodeTypes: ['microservice'],
        keywords: ['module', 'package', 'workspace', 'monorepo', 'domain'],
        what: 'Code organized into cohesive, loosely coupled modules.',
        why: 'Clear boundaries make the system understandable and independently testable.',
        fix: 'Organize code by feature/domain with explicit module boundaries and minimal cross-module coupling.',
      },
      {
        id: 'interoperability',
        label: 'Interoperability',
        icon: Plug,
        nodeTypes: ['api-gateway'],
        keywords: ['openapi', 'swagger', 'graphql-federation', 'grpc'],
        packages: ['swagger-ui-express', '@apollo/server', 'graphql', '@grpc/grpc-js'],
        what: 'Well-defined interfaces other systems can integrate against.',
        why: 'Stable contracts let clients and partners build without breaking on every change.',
        fix: 'Publish a versioned API contract (OpenAPI/GraphQL schema) and keep backward compatibility within a major version.',
      },
      {
        id: 'compliance',
        label: 'Compliance',
        icon: FileCheck,
        keywords: ['gdpr', 'hipaa', 'soc2', 'pci', 'compliance', 'audit log'],
        what: 'Meeting legal and regulatory data requirements.',
        why: 'Non-compliance carries fines and blocks enterprise sales.',
        fix: 'Map the applicable regime (GDPR, SOC 2, HIPAA), then implement audit logging, data retention, and access controls to match.',
      },
      {
        id: 'user-experience',
        label: 'User Experience',
        icon: Smile,
        nodeTypes: ['cdn'],
        keywords: ['ssr', 'accessib', 'a11y', 'lighthouse', 'web vitals'],
        what: 'How fast and pleasant the product feels to real users.',
        why: 'Architecture choices (edge, SSR, caching) directly shape perceived speed.',
        fix: 'Optimize Core Web Vitals: serve from the edge, cache aggressively, and code-split the frontend.',
      },
      {
        id: 'microservices-architecture',
        label: 'Microservices Architecture',
        icon: Workflow,
        nodeTypes: ['microservice'],
        keywords: ['docker-compose', 'kubernetes', 'service-mesh'],
        what: 'An architectural style of small services over a shared monolith.',
        why: 'Right for large teams and independent scaling; overkill for small ones.',
        fix: 'Adopt microservices only where independent scaling/deploy justifies the operational cost; otherwise keep a modular monolith.',
      },
      {
        id: 'performance-testing',
        label: 'Performance Testing',
        icon: FlaskConical,
        requiresProof: true,
        keywords: ['k6', 'load test', 'benchmark', 'artillery', 'jmeter', 'perf test'],
        packages: ['k6', 'artillery', 'autocannon'],
        what: 'Measuring behavior under realistic and peak load.',
        why: 'You cannot trust scalability claims you never tested.',
        fix: 'Add load tests (k6 or Artillery) to CI that assert latency and throughput budgets at target concurrency.',
      },
      {
        id: 'mindset-shift',
        label: 'Mindset Shift',
        icon: Brain,
        requiresProof: true,
        keywords: ['observability', 'sre', 'devops', 'iac', 'postmortem'],
        what: 'Operating with an SRE/DevOps culture: own reliability end to end.',
        why: 'Tools alone do not make a system enterprise-grade; practices do.',
        fix: 'Adopt SRE practices: SLOs, blameless postmortems, infrastructure as code, and on-call ownership.',
      },
    ],
  },
  {
    id: 'api-security',
    title: 'API Security',
    color: '#EF4444',
    cards: [
      {
        id: 'frontend-security',
        label: 'Frontend Security',
        icon: ShieldAlert,
        securityStep: true,
        keywords: ['xss', 'csp', 'content security policy', 'sanitiz'],
        negativeKeywords: ['dangerouslysetinnerhtml'],
        packages: ['dompurify', 'sanitize-html'],
        criticalIfMissing: true,
        what: 'Protecting the browser surface: XSS, CSP, and safe rendering.',
        why: 'The frontend is directly exposed; XSS leads to account takeover.',
        fix: 'Add a strict Content-Security-Policy, escape all dynamic output, and never inject unsanitized HTML.',
      },
      {
        id: 'access-control',
        label: 'Access Control',
        icon: UserCog,
        nodeTypes: ['auth-service'],
        securityStep: true,
        keywords: ['authoriz', 'rbac', 'permission', 'access control', 'idor'],
        criticalIfMissing: true,
        what: 'Enforcing who can do what on every endpoint.',
        why: 'Broken access control is the #1 OWASP API risk.',
        fix: 'Enforce authorization on every endpoint server-side, checking object ownership to prevent IDOR.',
      },
      {
        id: 'business-logic-abuse',
        label: 'Business Logic Abuse',
        icon: CircuitBoard,
        securityStep: true,
        requiresProof: true,
        keywords: ['business logic', 'workflow abuse', 'race condition', 'idempot'],
        what: 'Misusing valid flows (replay, race conditions, quota bypass).',
        why: 'These pass input validation yet still cause fraud or data corruption.',
        fix: 'Add idempotency keys, server-side invariant checks, and rate/quota enforcement on sensitive flows.',
      },
      {
        id: 'external-apis',
        label: 'External APIs',
        icon: Globe2,
        securityStep: true,
        requiresProof: true,
        keywords: ['third party', 'external api', 'webhook', 'api key', 'outbound'],
        what: 'Safely calling and trusting third-party services.',
        why: 'Outbound calls and webhooks expand the trust boundary and leak secrets if mishandled.',
        fix: 'Validate and verify webhook signatures, store third-party keys in a secret manager, and time-out outbound calls.',
      },
      {
        id: 'ssrf',
        label: 'SSRF',
        icon: CloudOff,
        securityStep: true,
        keywords: ['ssrf', 'server-side request forgery', 'url fetch', 'metadata endpoint'],
        criticalIfMissing: true,
        what: 'Server-Side Request Forgery: tricking the server into making requests.',
        why: 'SSRF can reach internal services and cloud metadata to steal credentials.',
        fix: 'Allowlist outbound destinations, block requests to internal/metadata IP ranges, and never fetch user-supplied URLs raw.',
      },
      {
        id: 'sensitive-data-exposure',
        label: 'Sensitive Data Exposure',
        icon: Eye,
        securityStep: true,
        keywords: ['public bucket', 'public-read', 'exposed', 'leak', 'pii', 'plaintext'],
        criticalIfMissing: true,
        what: 'Data reachable without authorization (public buckets, verbose errors).',
        why: 'Leaked PII or secrets are immediately and irreversibly damaging.',
        fix: 'Make buckets private, strip secrets from responses and logs, and encrypt sensitive fields at rest.',
      },
      {
        id: 'input-validation',
        label: 'Input Validation',
        icon: FileCheck,
        securityStep: true,
        keywords: ['validation', 'zod', 'sanitiz', 'injection', 'schema'],
        packages: ['zod', 'joi', 'yup', 'class-validator', 'ajv'],
        criticalIfMissing: true,
        what: 'Validating and sanitizing all untrusted input at the boundary.',
        why: 'Missing validation is the root of injection, XSS, and corruption bugs.',
        fix: 'Validate every request body and query with a schema (Zod) and reject malformed input before processing.',
      },
      {
        id: 'rate-limiting',
        label: 'Rate Limiting',
        icon: Timer,
        securityStep: true,
        keywords: ['rate limit', 'ratelimit', 'quota'],
        packages: ['express-rate-limit', 'rate-limiter-flexible', 'bottleneck', '@fastify/rate-limit'],
        criticalIfMissing: true,
        what: 'Capping request volume per client.',
        why: 'Without it, brute-force, scraping, and abuse run unchecked.',
        fix: 'Add per-client rate limiting at the gateway/middleware with sensible burst and sustained limits.',
      },
      {
        id: 'api-inventory',
        label: 'API Inventory',
        icon: ClipboardList,
        securityStep: true,
        requiresProof: true,
        keywords: ['openapi', 'swagger', 'api spec', 'endpoint inventory'],
        packages: ['swagger-ui-express', 'swagger-jsdoc', '@apollo/server'],
        what: 'A complete, current catalog of every exposed endpoint.',
        why: 'You cannot secure endpoints you do not know exist (shadow APIs).',
        fix: 'Generate and publish an OpenAPI spec from the routes and track it in CI so no endpoint is undocumented.',
      },
      {
        id: 'configuration-security',
        label: 'Configuration Security',
        icon: ServerCog,
        securityStep: true,
        keywords: ['security header', 'misconfig', 'default credential', 'debug mode'],
        packages: ['helmet', '@fastify/helmet'],
        criticalIfMissing: true,
        what: 'Secure defaults: headers, CORS, and no debug in production.',
        why: 'Misconfiguration is a top OWASP risk and is easy to ship by accident.',
        fix: 'Lock down CORS, set security headers (HSTS, X-Content-Type-Options), and disable debug endpoints in production.',
      },
    ],
  },
  {
    id: 'observability',
    title: 'Observability',
    color: '#A855F7',
    cards: [
      {
        id: 'structured-logging',
        label: 'Structured Logging',
        icon: ScrollText,
        keywords: ['winston', 'pino', 'bunyan', 'log-level'],
        packages: ['winston', 'pino', 'bunyan', '@aws-lambda-powertools/logger'],
        criticalIfMissing: true,
        what: 'Machine-parseable logs with consistent fields.',
        why: 'Unstructured logs are nearly useless during a real incident.',
        fix: 'Adopt a structured logger (pino or winston) emitting JSON with request IDs and consistent fields.',
      },
      {
        id: 'metrics-collection',
        label: 'Metrics Collection',
        icon: BarChart3,
        requiresProof: true,
        keywords: ['prometheus', 'metrics', 'statsd', 'datadog', 'opentelemetry'],
        packages: ['prom-client', 'hot-shots', '@opentelemetry/metrics'],
        what: 'Time-series metrics for latency, throughput, and errors.',
        why: 'Metrics are how you see system health before users complain.',
        fix: 'Export RED metrics (rate, errors, duration) via Prometheus/OpenTelemetry and dashboard them.',
      },
      {
        id: 'distributed-tracing',
        label: 'Distributed Tracing',
        icon: GitBranch,
        requiresProof: true,
        keywords: ['tracing', 'opentelemetry', 'jaeger', 'trace id', 'span'],
        packages: ['@opentelemetry/api', 'dd-trace', 'jaeger-client', 'zipkin'],
        what: 'End-to-end traces of a request across services.',
        why: 'The only practical way to debug latency in a multi-service system.',
        fix: 'Instrument services with OpenTelemetry tracing and propagate trace context across calls.',
      },
      {
        id: 'alerting-rules',
        label: 'Alerting Rules',
        icon: BellRing,
        keywords: ['alert', 'pagerduty', 'opsgenie', 'alertmanager', 'on-call'],
        criticalIfMissing: true,
        what: 'Automated alerts when key signals breach thresholds.',
        why: 'Detection without alerting means you find out from users.',
        fix: 'Define alert rules on error rate and latency SLOs and route them to an on-call channel.',
      },
      {
        id: 'health-checks',
        label: 'Health Checks',
        icon: HeartPulse,
        keywords: ['health check', 'healthz', 'readiness', 'liveness', '/health'],
        packages: ['@godaddy/terminus', 'terminus', 'express-healthcheck'],
        criticalIfMissing: true,
        what: 'Endpoints that report whether a service is alive and ready.',
        why: 'Orchestrators and load balancers need them to route around bad instances.',
        fix: 'Expose liveness and readiness endpoints and wire them into the load balancer/orchestrator.',
      },
      {
        id: 'uptime-monitoring',
        label: 'Uptime Monitoring',
        icon: MonitorCheck,
        requiresProof: true,
        keywords: ['uptime', 'pingdom', 'statuspage', 'synthetic', 'heartbeat'],
        what: 'External checks that the service is reachable.',
        why: 'Catches total outages that internal metrics can miss.',
        fix: 'Add external uptime monitoring (synthetic checks) against critical endpoints with alerting.',
      },
      {
        id: 'error-tracking',
        label: 'Error Tracking',
        icon: Bug,
        keywords: ['sentry', 'error tracking', 'bugsnag', 'rollbar'],
        packages: ['@sentry/node', '@sentry/react', '@sentry/browser', 'bugsnag', 'rollbar'],
        criticalIfMissing: true,
        what: 'Aggregated, deduplicated capture of runtime exceptions.',
        why: 'Errors buried in logs go unnoticed until they are widespread.',
        fix: 'Integrate an error tracker (Sentry) on frontend and backend with release and user context.',
      },
      {
        id: 'audit-logging',
        label: 'Audit Logging',
        icon: FileCheck,
        requiresProof: true,
        keywords: ['audit log', 'audit trail', 'who did what', 'activity log'],
        what: 'An immutable record of security-relevant actions.',
        why: 'Required for compliance and indispensable during investigations.',
        fix: 'Record an append-only audit trail of auth and privileged actions with actor, time, and target.',
      },
    ],
  },
  {
    id: 'resilience',
    title: 'Resilience',
    color: '#F59E0B',
    cards: [
      {
        id: 'circuit-breaker',
        label: 'Circuit Breaker',
        icon: CircuitBoard,
        criticalIfMissing: true,
        keywords: ['circuit breaker', 'opossum', 'hystrix', 'breaker'],
        packages: ['opossum', 'cockatiel', 'resilience4j'],
        what: 'Stops calling a failing dependency to let it recover.',
        why: 'Prevents one slow dependency from cascading into a full outage.',
        fix: 'Wrap unreliable downstream calls in a circuit breaker (e.g. opossum) with a fallback path.',
      },
      {
        id: 'retry-logic',
        label: 'Retry Logic',
        icon: RefreshCw,
        keywords: ['backoff', 'exponential-backoff', 'axios-retry', 'p-retry'],
        packages: ['axios-retry', 'p-retry', 'retry', 'cockatiel'],
        what: 'Re-attempting transient failures with backoff.',
        why: 'Most network failures are transient; naive code gives up on the first blip.',
        fix: 'Add retries with exponential backoff and jitter to idempotent outbound calls, capped by a deadline.',
      },
      {
        id: 'timeout-handling',
        label: 'Timeout Handling',
        icon: Hourglass,
        keywords: ['request-timeout', 'connection-timeout', 'abortcontroller'],
        criticalIfMissing: true,
        what: 'Bounding how long any call may block.',
        why: 'Missing timeouts let one hung call exhaust the connection pool.',
        fix: 'Set explicit timeouts (AbortController/deadlines) on every outbound network and DB call.',
      },
      {
        id: 'failover-strategy',
        label: 'Failover Strategy',
        icon: GitFork,
        criticalIfMissing: true,
        partialTypes: ['load-balancer'],
        keywords: ['failover', 'standby', 'replica promotion', 'multi-az'],
        what: 'Automatically switching to a healthy replica on failure.',
        why: 'Determines recovery time when a primary instance or zone dies.',
        fix: 'Run redundant instances across zones with automatic failover and tested promotion of replicas.',
      },
      {
        id: 'disaster-recovery',
        label: 'Disaster Recovery',
        icon: LifeBuoy,
        keywords: ['disaster recovery', 'rto', 'rpo', 'restore', 'failback'],
        criticalIfMissing: true,
        what: 'A tested plan to recover from catastrophic loss.',
        why: 'Backups you have never restored are not a recovery plan.',
        fix: 'Define RTO/RPO targets and run regular restore drills from backups into a clean environment.',
      },
      {
        id: 'graceful-degradation',
        label: 'Graceful Degradation',
        icon: ArrowDownUp,
        keywords: ['circuit-breaker', 'degraded-mode', 'feature-flag'],
        what: 'Shedding non-critical features instead of failing entirely.',
        why: 'A partially working product beats a blank error page.',
        fix: 'Add fallbacks for non-critical dependencies so core flows keep working when extras fail.',
      },
      {
        id: 'bulkhead-pattern',
        label: 'Bulkhead Pattern',
        icon: Split,
        keywords: ['bulkhead', 'isolation', 'pool isolation', 'partition'],
        what: 'Isolating resources so one overload cannot sink everything.',
        why: 'Keeps a runaway workload from starving unrelated traffic.',
        fix: 'Partition connection pools and worker capacity per workload so one cannot exhaust the others.',
      },
      {
        id: 'chaos-engineering',
        label: 'Chaos Engineering',
        icon: FlaskConical,
        requiresProof: true,
        keywords: ['chaos', 'fault injection', 'gameday', 'chaos monkey'],
        what: 'Deliberately injecting failure to validate resilience.',
        why: 'Proves recovery works before a real incident does.',
        fix: 'Run periodic game-days that inject failures (kill instances, add latency) and verify graceful recovery.',
      },
    ],
  },
  {
    id: 'data-architecture',
    title: 'Data Architecture',
    color: '#22C55E',
    cards: [
      {
        id: 'database-sharding',
        label: 'Database Sharding',
        icon: Split,
        requiresProof: true,
        keywords: ['shard', 'sharding', 'partition key', 'citus', 'vitess'],
        what: 'Splitting data across nodes by a shard key.',
        why: 'The path past a single database’s write ceiling.',
        fix: 'Plan a shard key and introduce sharding (Citus/Vitess) before the primary database becomes the bottleneck.',
      },
      {
        id: 'read-replicas',
        label: 'Read Replicas',
        icon: Copy,
        requiresProof: true,
        partialTypes: ['postgres', 'mysql'],
        keywords: ['read replica', 'replica', 'follower', 'standby'],
        what: 'Read-only copies that offload queries from the primary.',
        why: 'Cheapest way to scale read-heavy workloads.',
        fix: 'Add read replicas and route read-only queries to them, keeping writes on the primary.',
      },
      {
        id: 'caching-strategy',
        label: 'Caching Strategy',
        icon: Zap,
        nodeTypes: ['cache', 'redis'],
        keywords: ['redis', 'memcached', 'cache-control', 'stale-while-revalidate'],
        packages: ['ioredis', 'redis', 'node-cache'],
        what: 'A deliberate plan for what to cache, where, and how to invalidate.',
        why: 'Caching without an invalidation strategy serves stale, wrong data.',
        fix: 'Define cache layers, TTLs, and explicit invalidation on writes for the hottest read paths.',
      },
      {
        id: 'consistency-model',
        label: 'Consistency Model',
        icon: Combine,
        keywords: ['consistency', 'eventual', 'transaction', 'isolation level', 'acid'],
        what: 'The chosen trade-off between consistency and availability.',
        why: 'Implicit consistency choices cause subtle, hard-to-debug data bugs.',
        fix: 'Make consistency explicit: use transactions where strong consistency is required and document where eventual is acceptable.',
      },
      {
        id: 'data-partitioning',
        label: 'Data Partitioning',
        icon: Layers,
        requiresProof: true,
        keywords: ['partition', 'time partition', 'range partition', 'tablespace'],
        what: 'Organizing a table’s rows into partitions.',
        why: 'Keeps large tables and their queries fast and maintainable.',
        fix: 'Partition large tables (by time or tenant) so queries and retention stay efficient at volume.',
      },
      {
        id: 'backup-strategy',
        label: 'Backup Strategy',
        icon: Save,
        requiresProof: true,
        keywords: ['backup', 'snapshot', 'pg_dump', 'point-in-time', 'pitr'],
        what: 'Regular, restorable copies of the data.',
        why: 'The last line of defense against corruption, deletion, and ransomware.',
        fix: 'Automate encrypted backups with point-in-time recovery and verify restores on a schedule.',
      },
      {
        id: 'encryption-at-rest',
        label: 'Data Encryption at Rest',
        icon: Lock,
        nodeTypes: ['kms'],
        keywords: ['encryption at rest', 'sse', 'serverside encryption', 'encrypted', 'pgcrypto'],
        criticalIfMissing: true,
        what: 'Encrypting stored data on disk.',
        why: 'Protects data if storage media or backups are stolen.',
        fix: 'Enable encryption at rest on databases and buckets, with keys managed by a KMS.',
      },
      {
        id: 'migration-strategy',
        label: 'Migration Strategy',
        icon: GitMerge,
        requiresProof: true,
        keywords: ['migration', 'prisma migrate', 'flyway', 'liquibase', 'schema change'],
        packages: ['prisma', 'knex', 'typeorm', 'node-pg-migrate'],
        what: 'A safe, versioned process for schema changes.',
        why: 'Ad-hoc schema edits cause downtime and data loss.',
        fix: 'Use versioned, reversible migrations (Prisma/Flyway) applied through CI, with expand-then-contract for breaking changes.',
      },
    ],
  },
  {
    id: 'security-hardening',
    title: 'Security Hardening',
    color: '#F43F5E',
    cards: [
      {
        id: 'zero-trust',
        label: 'Zero Trust Architecture',
        icon: ShieldCheck,
        requiresProof: true,
        keywords: ['zero trust', 'beyondcorp', 'never trust', 'identity-aware'],
        what: 'Trust nothing by default; verify every request and identity.',
        why: 'Perimeter-only security fails once an attacker is inside.',
        fix: 'Authenticate and authorize every internal call; drop implicit network trust between services.',
      },
      {
        id: 'secrets-management',
        label: 'Secrets Management',
        icon: FileKey,
        nodeTypes: ['kms'],
        keywords: ['vault', 'aws-secrets', 'azure-keyvault', 'doppler'],
        packages: ['dotenv-vault', '@aws-sdk/client-secrets-manager', 'vault', 'node-vault', '@azure/keyvault-secrets'],
        criticalIfMissing: true,
        what: 'Storing credentials outside code in a managed vault.',
        why: 'Hardcoded secrets in repos are a top cause of breaches.',
        fix: 'Move all secrets into a secret manager (Vault/AWS Secrets Manager) and rotate anything previously committed.',
      },
      {
        id: 'mtls',
        label: 'mTLS',
        icon: Fingerprint,
        criticalIfMissing: true,
        keywords: ['mtls', 'mutual tls', 'client certificate', 'mutual authentication'],
        packages: ['@grpc/grpc-js', 'spiffe', 'mutual-tls'],
        what: 'Mutual TLS so both sides of a connection prove identity.',
        why: 'Stops service impersonation on internal east-west traffic.',
        fix: 'Enable mutual TLS between services (via a mesh or cert tooling) so both peers authenticate.',
      },
      {
        id: 'ddos-protection',
        label: 'DDoS Protection',
        icon: CloudOff,
        nodeTypes: ['ddos-protection'],
        keywords: ['ddos', 'cloudflare', 'shield', 'rate limit edge', 'scrubbing'],
        criticalIfMissing: true,
        what: 'Absorbing and filtering volumetric attack traffic at the edge.',
        why: 'An undefended origin can be knocked offline cheaply.',
        fix: 'Put the app behind edge DDoS protection (Cloudflare/AWS Shield) with rate limiting at the edge.',
      },
      {
        id: 'waf',
        label: 'WAF',
        icon: Shield,
        nodeTypes: ['waf'],
        keywords: ['waf', 'web application firewall', 'modsecurity', 'owasp ruleset'],
        criticalIfMissing: true,
        what: 'A firewall that inspects HTTP traffic for known attacks.',
        why: 'Blocks injection, XSS, and bad bots before they reach the app.',
        fix: 'Deploy a WAF with the OWASP core ruleset in front of the application edge.',
      },
      {
        id: 'penetration-testing',
        label: 'Penetration Testing',
        icon: SprayCan,
        requiresProof: true,
        keywords: ['pentest', 'penetration test', 'red team', 'security assessment'],
        what: 'Authorized attacks to find vulnerabilities before attackers do.',
        why: 'Automated scans miss logic and chained vulnerabilities a human finds.',
        fix: 'Schedule regular third-party penetration tests and track remediation of findings to closure.',
      },
      {
        id: 'dependency-scanning',
        label: 'Dependency Scanning',
        icon: Search,
        keywords: ['npm audit', 'snyk', 'dependabot', 'trivy', 'cve', 'vulnerab'],
        packages: ['.snyk', 'dependabot.yml', 'trivy', 'snyk'],
        criticalIfMissing: true,
        what: 'Automatically flagging vulnerable third-party packages.',
        why: 'Most app code is dependencies; their CVEs are your CVEs.',
        fix: 'Run dependency scanning (npm audit/Snyk/Dependabot) in CI and fail builds on high-severity CVEs.',
      },
      {
        id: 'rbac',
        label: 'RBAC',
        icon: UserCog,
        nodeTypes: ['auth-service'],
        keywords: ['rbac', 'role', 'permission', 'authoriz', 'policy'],
        criticalIfMissing: true,
        what: 'Role-based access control over actions and resources.',
        why: 'Without roles, every authenticated user is effectively an admin.',
        fix: 'Define roles and permissions and enforce them server-side on every privileged action.',
      },
    ],
  },
  {
    id: 'deployment-scale',
    title: 'Deployment and Scale',
    color: '#38BDF8',
    cards: [
      {
        id: 'cicd-pipeline',
        label: 'CI/CD Pipeline',
        icon: GitMerge,
        keywords: ['github-actions', 'gitlab-ci', 'circleci'],
        packages: ['.github/workflows', '.gitlab-ci.yml', 'jenkinsfile', '.circleci'],
        criticalIfMissing: true,
        what: 'Automated build, test, and deploy on every change.',
        why: 'Manual deploys are slow and error-prone; CI/CD is table stakes.',
        fix: 'Add a CI/CD pipeline that lints, type-checks, tests, scans, and deploys on every push to main.',
      },
      {
        id: 'blue-green',
        label: 'Blue-Green Deployment',
        icon: Combine,
        requiresProof: true,
        keywords: ['blue-green', 'blue green', 'swap environment', 'cutover'],
        what: 'Two identical environments swapped at release time.',
        why: 'Enables instant rollback and zero-downtime releases.',
        fix: 'Deploy to an idle environment, smoke-test it, then cut traffic over with instant rollback.',
      },
      {
        id: 'canary-releases',
        label: 'Canary Releases',
        icon: Bird,
        requiresProof: true,
        keywords: ['canary', 'progressive delivery', 'percent rollout', 'argo rollouts'],
        what: 'Releasing to a small slice of traffic first.',
        why: 'Catches regressions on real traffic before a full rollout.',
        fix: 'Roll out new versions to a small traffic percentage with automated rollback on error-rate regression.',
      },
      {
        id: 'auto-scaling',
        label: 'Auto Scaling',
        icon: Expand,
        criticalIfMissing: true,
        partialTypes: ['load-balancer'],
        keywords: ['hpa', 'scaling policy', 'scale-out', 'asg'],
        what: 'Adding/removing capacity automatically with demand.',
        why: 'Keeps the system responsive at peak and cheap when idle.',
        fix: 'Configure autoscaling on the app tier driven by CPU/latency, with sane min/max bounds.',
      },
      {
        id: 'iac',
        label: 'Infrastructure as Code',
        icon: FileCode,
        keywords: ['terraform', 'pulumi', 'cloudformation', 'infrastructure as code', 'iac'],
        packages: ['aws-cdk-lib', '@pulumi/pulumi', 'pulumi', 'cdktf'],
        criticalIfMissing: true,
        what: 'Provisioning infrastructure from version-controlled code.',
        why: 'Click-ops drifts and is impossible to review or reproduce.',
        fix: 'Define all infrastructure in code (Terraform/Pulumi) reviewed and applied through CI.',
      },
      {
        id: 'multi-region',
        label: 'Multi-Region',
        icon: Globe2,
        requiresProof: true,
        keywords: ['multi-region', 'multi region', 'region failover'],
        what: 'Running across multiple geographic regions.',
        why: 'Reduces global latency and survives a regional outage.',
        fix: 'Plan a multi-region topology with data replication and region-aware routing for latency and DR.',
      },
      {
        id: 'sla-slo-sli',
        label: 'SLA/SLO/SLI',
        icon: Gauge,
        keywords: ['slo', 'sla', 'sli', 'error budget', 'service level'],
        criticalIfMissing: true,
        what: 'Defined service-level objectives, indicators, and agreements.',
        why: 'Without targets, reliability is a feeling rather than a measurement.',
        fix: 'Define SLIs (latency, error rate), set SLOs with error budgets, and alert when budgets burn.',
      },
      {
        id: 'cost-monitoring',
        label: 'Cost Monitoring',
        icon: DollarSign,
        requiresProof: true,
        keywords: ['cost monitor', 'billing alert', 'cost explorer', 'finops', 'spend'],
        what: 'Tracking and alerting on cloud spend.',
        why: 'Cost surprises are budget incidents; catch them early.',
        fix: 'Enable cost monitoring with per-service tagging and billing alerts on anomalous spend.',
      },
    ],
  },
];
